apiVersion: v1
kind: PersistentVolume
metadata:
  name: chesstango-syzygy-pv
spec:
  capacity:
    storage: 10Gi # Declared capacity, not enforced for hostPath
  accessModes:
    - ReadOnlyMany # Allows multiple nodes to mount read-only
  hostPath:
    path: "/mnt/syzygy"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual-hostpath"
