apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chesstango-syzygy-pvc
spec:
  accessModes:
    - ReadOnlyMany # Requesting read-only access
  resources:
    requests:
      storage: 10Gi # Requesting storage that matches the PV's declared capacity
  storageClassName: "manual-hostpath"
