apiVersion: apps/v1
kind: Deployment
metadata:
  name: uci-arena-worker
  labels:
    app: uci-arena-worker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: uci-arena-worker
  template:
    metadata:
      name: uci-arena-worker
      labels:
        app: uci-arena-worker
    spec:
      containers:
        - name: uci-arena-worker
          image: coriamauricio/uci-arena-worker:1.2.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "900m"
          envFrom:
            - configMapRef:
                name: match-worker-config
          volumeMounts:
            - name: engine-volume
              mountPath: /engines
            - name: books-volume
              mountPath: /books/
      volumes:
        - name: books-volume
          persistentVolumeClaim:
            claimName: chesstango-book-pvc
        - name: engine-volume
          persistentVolumeClaim:
            claimName: engines-pvc
      restartPolicy: Always
      